### ISSUE TITLE
Properties that have single allOf are not rendered

### ISSUE THREAD

**Issue by staticf0x** [staticf0x/schema-viewer#4]
Example:

```yaml
some_prop:
  description: Some Prop
  allOf:
    - $ref: path/to/subschema.yaml
```

is not read because the code currently expects `allOf` to be inside `items`.
